tags/Cadet.PhysicalAccounting 1.0/Cadet.PhysicalAccounting.Web/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cadet.PhysicalAccounting.DBProxy;

namespace Cadet.PhysicalAccounting.Web.Controllers
{
    public class CourseController : Controller
    {
        private DBContext db = new DBContext();

        //
        // GET: /Course/

        public ActionResult Index(int facultyId = -1)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            var courses = db.Courses.Where(c => c.FacultyId == facultyId).Include("Faculty");
            var fac = db.Faculties.First(f=>f.Id == facultyId);
            ViewBag.FacultyName = fac != null ? fac.Title : "Несуществующий факультет";
            ViewBag.FacultyId = facultyId;
            return View(courses.ToList().OrderBy(c=>c.Number));
        }

        //
        // GET: /Course/Details/5

        public ActionResult Details(int id = 0)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Course course = db.Courses.Single(c => c.Id == id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        //
        // GET: /Course/Create

        public ActionResult Create(int facultyId = -1)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            ViewBag.FacultyId = new SelectList(db.Faculties, "Id", "Title");
            
            ViewBag.SemesterId = new SelectList(db.Semesters, "Id", "Id");
            ViewBag.SelectedFacultyId = facultyId;
            return View();
        }

        //
        // POST: /Course/Create

        [HttpPost]
        public ActionResult Create(Course course)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            if (ModelState.IsValid)
            {
                db.Courses.AddObject(course);
                db.SaveChanges();
                FacultyTreeMaker.RefreshFacultyTreeModel();
                return RedirectToAction("Index", new  {facultyId = course.FacultyId });
            }

            ViewBag.FacultyId = new SelectList(db.Faculties, "Id", "Title", course.FacultyId);
            return View(course);
        }

        //
        // GET: /Course/Edit/5

        public ActionResult Edit(int id = 0)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Course course = db.Courses.Single(c => c.Id == id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.FacultyId = new SelectList(db.Faculties, "Id", "Title", course.FacultyId);
            return View(course);
        }

        //
        // POST: /Course/Edit/5

        [HttpPost]
        public ActionResult Edit(Course course)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            if (ModelState.IsValid)
            {
                db.Courses.Attach(course);
                db.ObjectStateManager.ChangeObjectState(course, EntityState.Modified);
                db.SaveChanges();
                FacultyTreeMaker.RefreshFacultyTreeModel();
                return RedirectToAction("Index", new { facultyId = course.FacultyId });
            }
            ViewBag.FacultyId = new SelectList(db.Faculties, "Id", "Title", course.FacultyId);
            return View(course);
        }

        //
        // GET: /Course/Delete/5

        public ActionResult Delete(int id = 0)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Course course = db.Courses.Single(c => c.Id == id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        //
        // POST: /Course/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Course course = db.Courses.Single(c => c.Id == id);
            int facId = course.FacultyId;
            foreach (var group in course.Groups.ToList())
            {
                foreach (var cadet in group.Cadets.ToList())
                {
                    foreach (var result in cadet.Results.ToList())
                    {
                        db.Results.DeleteObject(result);
                    }
                    db.Cadets.DeleteObject(cadet);
                }
                db.Groups.DeleteObject(group);
            }
            db.Courses.DeleteObject(course);
            db.SaveChanges();
            FacultyTreeMaker.RefreshFacultyTreeModel();
            return RedirectToAction("Index", new { facultyId = facId });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

tags/Cadet.PhysicalAccounting 1.0/Cadet.PhysicalAccounting.Web/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cadet.PhysicalAccounting.DBProxy;

namespace Cadet.PhysicalAccounting.Web.Controllers
{
    public class GroupController : Controller
    {
        private DBContext db = new DBContext();

        //
        // GET: /Group/

        public ActionResult Index(int courseId = -1)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            var course = db.Courses.Where(c=>c.Id == courseId).Include("Faculty").FirstOrDefault();
            if (course != null)
            {
                ViewBag.FacultyName = course.Faculty.Title;
                ViewBag.CourseNumber = course.Number;
                ViewBag.CourseId = courseId;
                ViewBag.FacultyId = course.FacultyId;
            }

            var groups = db.Groups.Where(g=>g.CourseId == courseId).Include("Course");
            return View(groups.ToList().OrderBy(g=>g.Number));
        }

        //
        // GET: /Group/Details/5

        public ActionResult Details(int id = 0)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Group group = db.Groups.Single(g => g.Id == id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        //
        // GET: /Group/Create

        public ActionResult Create(int facultyId, int courseId)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            ViewBag.CourseId = new SelectList(db.Courses.Where(c=>c.FacultyId == facultyId), "Id", "Number",courseId);
            ViewBag.SemesterId = new SelectList(db.Semesters, "Id", "Number");

            ViewBag.SelectedCourseId = courseId;
            return View();
        }

        //
        // POST: /Group/Create

        [HttpPost]
        public ActionResult Create(Group group)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            if (ModelState.IsValid)
            {
                db.Groups.AddObject(group);
                db.SaveChanges();
                FacultyTreeMaker.RefreshFacultyTreeModel();
                return RedirectToAction("Index", new { courseId = group.CourseId});
            }

            ViewBag.CourseId = new SelectList(db.Courses, "Id", "Number", group.CourseId);
            ViewBag.SemesterId = new SelectList(db.Semesters, "Id", "Number", group.SemesterId);
            return View(group);
        }

        //
        // GET: /Group/Edit/5

        public ActionResult Edit(int id = 0)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Group group = db.Groups.Single(g => g.Id == id);
            if (group == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.CourseId = new SelectList(db.Courses.Where(c=>c.FacultyId == group.Course.FacultyId), "Id", "Number", group.CourseId);
            ViewBag.SemesterId = new SelectList(db.Semesters, "Id", "Number", group.SemesterId);
            return View(group);
        }

        //
        // POST: /Group/Edit/5

        [HttpPost]
        public ActionResult Edit(Group group)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            if (ModelState.IsValid)
            {
                db.Groups.Attach(group);
                db.ObjectStateManager.ChangeObjectState(group, EntityState.Modified);
                db.SaveChanges();
                FacultyTreeMaker.RefreshFacultyTreeModel();
                return RedirectToAction("Index", new { courseId = group.CourseId});
            }

            ViewBag.SemesterId = new SelectList(db.Semesters, "Id", "Number", group.SemesterId);
            ViewBag.CourseId = new SelectList(db.Courses, "Id", "Number", group.CourseId);
            return View(group);
        }

        //
        // GET: /Group/Delete/5

        public ActionResult Delete(int id = 0)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Group group = db.Groups.Single(g => g.Id == id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        //
        // POST: /Group/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Group group = db.Groups.Single(g => g.Id == id);
            int cId = group.CourseId;
            foreach (var cadet in group.Cadets.ToList())
            {
                foreach (var result in cadet.Results.ToList())
                {
                    db.Results.DeleteObject(result);
                }
                db.Cadets.DeleteObject(cadet);               
            }
            db.Groups.DeleteObject(group);
            db.SaveChanges();

            FacultyTreeMaker.RefreshFacultyTreeModel();
            return RedirectToAction("Index", new { courseId = cId });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

tags/Cadet.PhysicalAccounting 1.0/Cadet.PhysicalAccounting.Web/Views/Course/Create.cshtml
@model Cadet.PhysicalAccounting.DBProxy.Course

@{
    ViewBag.Title = "Добавить курс";
}

<h2></h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Курс</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FacultyId, "Факультет")
        </div>
        <div class="editor-field">
            @Html.DropDownList("FacultyId", String.Empty)
            @Html.ValidationMessageFor(model => model.FacultyId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Number, "Номер курса")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Number)
            @Html.ValidationMessageFor(model => model.Number)
        </div>
        <p>
            <button class="btn btn-success button-save" type="submit" value="Сохранить" ><i class="icon-ok  icon-white"></i><text> Сохранить</text></button>
            <button type="button" class="btn btn-danger button-back" title="Отмена" value="Отмена" onclick="location.href='@Url.Action("Index", new { facultyId = ViewBag.SelectedFacultyId})'" ><i class="icon-remove icon-white"></i><text> Отмена</text></button>
        </p>
    </fieldset>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

tags/Cadet.PhysicalAccounting 1.0/Cadet.PhysicalAccounting.Web/Views/Course/Delete.cshtml
@model Cadet.PhysicalAccounting.DBProxy.Course

@{
    ViewBag.Title = "Удаление курса";
}

<h2>Удалить курс</h2>

<h3>Вы уверены, что хотите удалить @Model.Number курс факультета @Model.Faculty.Title?</h3>

@using (Html.BeginForm()) {
    <p>
        <button class="btn btn-danger button-delete" type="submit" value="Удалить" ><i class="icon-ok icon-white"></i><text> Удалить</text></button>
        <button type="button" class="btn button-back" title="Отмена" value="Отмена" onclick="location.href='@Url.Action("Index", new { facultyId = Model.FacultyId})'" ><i class="icon-remove"></i><text> Отмена</text></button> 
    </p>
}

tags/Cadet.PhysicalAccounting 1.0/Cadet.PhysicalAccounting.Web/Views/Course/Details.cshtml
@model Cadet.PhysicalAccounting.DBProxy.Course

@{
    ViewBag.Title = "Просмотр";
}

<h2>Просмотр</h2>

<fieldset>
    <legend>Course</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Faculty.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Faculty.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Number)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Number)
    </div>


</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

tags/Cadet.PhysicalAccounting 1.0/Cadet.PhysicalAccounting.Web/Views/Course/Edit.cshtml
@model Cadet.PhysicalAccounting.DBProxy.Course

@{
    ViewBag.Title = "Редактирование курса";
}

<h2>Редактирование курса</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Курс</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.FacultyId, "Факультет")
        </div>
        <div class="editor-field">
            @Html.DropDownList("FacultyId", String.Empty)
            @Html.ValidationMessageFor(model => model.FacultyId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Number, "Номер курса")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Number)
            @Html.ValidationMessageFor(model => model.Number)
        </div>
        <p>
            <button class="btn btn-success button-save" type="submit" value="Сохранить" ><i class="icon-ok  icon-white"></i><text> Сохранить</text></button>
            <button type="button" class="btn btn-danger button-back" title="Отмена" value="Отмена" onclick="location.href='@Url.Action("Index", new {facultyId = Model.FacultyId })'" ><i class="icon-remove icon-white"></i><text> Отмена</text></button>
        </p>
    </fieldset>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

tags/Cadet.PhysicalAccounting 1.0/Cadet.PhysicalAccounting.Web/Views/Course/Index.cshtml
@model IEnumerable<Cadet.PhysicalAccounting.DBProxy.Course>

@{
    ViewBag.Title = "Курсы";
}

<h2>Курсы факультета @ViewBag.FacultyName
<button type="button" class="btn btn-success button-add" title="Добавить курс" value="Добавить курс" onclick="location.href='@Url.Action("Create", new { facultyId = ViewBag.FacultyId })'"><i class="icon-plus"></i></button>

</h2>


<table class="table  table-bordered table-striped ">
    <thead>
        <th>
        <b style="font-size:medium">
            <text>Курс</text>
        </b>
        </th>
        <th></th>
    </thead>
@foreach (var item in Model) {
    <tr>
        <td>
        <b style="font-size:medium">
            @Html.ActionLink(item.Number + " курс", "Index", "Group", new { courseId = item.Id }, null)
         </b>
        </td>
        <td class="table-buttons-menu">
            <button type="button" class="btn btn-warning button-edit" value="Редактировать" title="Редактировать" onclick="location.href='@Url.Action("Edit", new { id = item.Id })'" ><i class="icon-pencil"></i></button>
            <!--<input type="button" class="button-view" title="Просмотр" value="Просмотр" onclick="location.href='@Url.Action("Details", new { id = item.Id })'" />-->
            <button type="button" class="btn btn-danger button-delete" value="Удалить" title="Удалить" onclick="location.href='@Url.Action("Delete", new { id = item.Id })'"> <i class="icon-trash"></i></button>
        </td>
    </tr>
}

</table>

<p>
    <button type="button" class="btn btn-info button-back" title="Назад" value="Назад" style="color:Black" onclick="location.href='@Url.Action("Index","Faculty")'"><i class="icon-arrow-left"> </i> <text> Назад</text></button>
</p>