tags/Cadet.PhysicalAccounting 1.0/Cadet.PhysicalAccounting.Web/Controllers/CadetsDataController.cs
using System;
using System.Collections.Generic;
using System.Data.Objects;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cadet.PhysicalAccounting.DBProxy;
using Cadet.PhysicalAccounting.Web.Models;
using Cadet.PhysicalAccounting.Web.Models.MockGenerators;

namespace Cadet.PhysicalAccounting.Web.Controllers
{
    public class CadetsDataController : Controller
    {
        public ActionResult Index(int groupId = 0)
        {
            var model = new SessionData();
            model.GroupId = groupId;
            ViewData.Add("currentGroupId", groupId);

            if (groupId > 0)
            {
                using (var ctx = new DBProxy.DBContext())
                {
                    try
                    {
                        model.Cadets = ctx.Cadets.Where(o => o.GroupId == groupId).ToList();
                        model.Group = ctx.Groups.Single(o => o.Id == groupId);
                        model.Course = model.Group.Course;
                        model.Faculty = model.Group.Course.Faculty;
                    }
                    catch (Exception)
                    {
                        model.Info.ErrorMessage =
                            "Произошла ошибка при получении информации из базы данных, возможно искомых записей не существует";
                    }
                }
            }
            else if (groupId < 0)
            {
                // Test data
                model.Info.InfoMessage = "Отображены тестовые данные";

                model.Cadets = CadetsGenerator.GetCadetsList(5);
                model.Group.Number = 5;
                model.Course.Number = 3;
                model.Faculty.Number = 2;
            }
            else
            {
                model.Info.ErrorMessage = "Не указан идентификатор группы";
            }
            return View(model);
        }

        //[HttpPost]
        public ActionResult WriteResults(int groupId)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            using (var context = new DBContext())
            {
                var model = new SessionData {GroupId = groupId, SemesterId = 0};
                ViewData.Add("currentGroupId", groupId);

                FillData(context, model);
                model.CadetResults = model.Cadets.Select(cadet => new CadetResults {Cadet = cadet}).ToList();
                FillResults(context, model);

                return View(model);
            }
        }

        public ActionResult GetResults(int groupId, int semesterId)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            using (var context = new DBContext())
            {
                var model = new SessionData {SemesterId = (byte) semesterId, GroupId = groupId};
                ViewData.Add("groupId", groupId);

                FillData(context, model);
                model.CadetResults = model.Cadets.Select(cadet => new CadetResults {Cadet = cadet}).ToList();
                FillResults(context, model);

                return View("WriteResultsTablePartial", model);
            }
        }

        private static void FillResults(DBContext context, SessionData model)
        {
            try
            {
                foreach (var currentCadet in model.CadetResults)
                {
                    var cadet = currentCadet;
                    var results =
                        context.Results.Where(r => r.SemesterId == model.SemesterId && r.CadetId == cadet.Cadet.Id);

                    Result result;

                    result = results.SingleOrDefault(r => r.Norm.NormType.Id == NormsTypes.PowerId);

                    if (result != null)
                    {
                        model.PowerNormId = result.NormId;
                        cadet.Power = result.Value;
                    }

                    result = results.SingleOrDefault(r => r.Norm.NormType.Id == NormsTypes.AgilityId);

                    if (result != null)
                    {
                        model.AgilityNormId = result.NormId;
                        cadet.Agility = result.Value;
                    }

                    result = results.SingleOrDefault(r => r.Norm.NormType.Id == NormsTypes.SpeedId);

                    if (result != null)
                    {
                        model.SpeedNormId = result.NormId;
                        cadet.Speed = result.Value;
                    }

                    result = results.SingleOrDefault(r => r.Norm.NormType.Id == NormsTypes.EnduranceId);

                    if (result != null)
                    {
                        model.EnduranceNormId = result.NormId;
                        cadet.Endurance = result.Value;
                    }

                    result = results.SingleOrDefault(r => r.Norm.NormType.Id == NormsTypes.MilitaryId);

                    if (result != null)
                    {
                        model.MilitaryNormId = result.NormId;
                        cadet.Military = result.Value;
                    }
                }
            }
            catch (Exception ex)
            {
                model.Info.ErrorMessage = "Произошла ошибка при сохранении информации";
                throw;
            }
        }

        private static void FillData(DBContext context, SessionData model)
        {
            if (model.GroupId > 0)
            {
                try
                {
                    model.Cadets = context.Cadets.Where(o => o.GroupId == model.GroupId).ToList();
                    model.Group = context.Groups.Single(o => o.Id == model.GroupId);
                    model.Course = model.Group.Course;
                    model.Faculty = model.Group.Course.Faculty;

                    model.PowerNorms = new SelectList(
                        context.Norms.Where(norm => norm.NormType.Id == NormsTypes.PowerId).ToList(), "Id",
                        "Name");
                    model.AgilityNorms =
                        new SelectList(context.Norms.Where(norm => norm.NormType.Id == NormsTypes.AgilityId).ToList(),
                                       "Id", "Name");
                    model.SpeedNorms =
                        new SelectList(context.Norms.Where(norm => norm.NormType.Id == NormsTypes.SpeedId).ToList(),
                                       "Id", "Name");
                    model.EnduranceNorms =
                        new SelectList(context.Norms.Where(norm => norm.NormType.Id == NormsTypes.EnduranceId).ToList(), "Id",
                                       "Name");
                    model.MilitaryNorms =
                        new SelectList(context.Norms.Where(norm => norm.NormType.Id == NormsTypes.MilitaryId).ToList(), "Id",
                                       "Name");

                    model.Semesters = new SelectList(context.Semesters.ToList(), "Id", "Number");
                }
                catch (Exception)
                {
                    model.Info.ErrorMessage =
                        "Произошла ошибка при получении информации из базы данных, возможно искомых записей не существует";
                }
            }
            else
            {
                model.Info.ErrorMessage = "Не указан идентификатор группы";
            }
        }

        [HttpPost]
        public ActionResult WriteResults(SessionData model)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            using (var context = new DBContext())
            {
                FillData(context, model);

                for (int i = 0; i < model.CadetResults.Count; i++)
                {
                    model.CadetResults[i].Cadet = model.Cadets[i];
                }

                if (Validate(model))
                {
                    SaveModel(context, model);
                    model.Info.InfoMessage = "Результаты успешно сохранены";

                    return View(model);
                }

                return View(model);
            }
        }

        private void SaveModel(DBContext context, SessionData model)
        {
            try
            {
                foreach (var currentCadet in model.CadetResults)
                {
                    var cadet = currentCadet;
                    var results =
                        context.Results.Where(r => r.SemesterId == model.SemesterId && r.CadetId == cadet.Cadet.Id);

                    Result result;

                    if (model.PowerNormId > 0)
                    {
                        result = results.SingleOrDefault(r => r.Norm.NormType.Id == NormsTypes.PowerId);

                        if (result != null)
                        {
                            result.Value = cadet.Power;
                            result.NormId = model.PowerNormId;
                        }
                        else
                        {
                            context.Results.AddObject(new Result
                                {
                                    Value = cadet.Power,
                                    NormId = model.PowerNormId,
                                    CadetId = cadet.Cadet.Id,
                                    SemesterId = model.SemesterId
                                });
                        }
                    }

                    if (model.AgilityNormId > 0)
                    {
                        result = results.SingleOrDefault(r => r.Norm.NormType.Id == NormsTypes.AgilityId);

                        if (result != null)
                        {
                            result.Value = cadet.Agility;
                            result.NormId = model.AgilityNormId;
                        }
                        else

tags/Cadet.PhysicalAccounting 1.0/Cadet.PhysicalAccounting.Web/Views/CadetsData/Details.cshtml
@using Cadet.PhysicalAccounting.DBProxy
@model Cadet
@{
    ViewData["animation"] = true;
}
@section scripts
{
    <script type="text/javascript" src="../../Scripts/highcharts/highcharts.js"></script>
    <script type="text/javascript" src="../../Scripts/highcharts/modules/exporting.js"></script>
}
@Html.Partial("_ColumnGraphPartial", Model, ViewData)

<div class="subpage-header">Информация о курсанте</div>

@if (Model.Info.InfoMessage != null)
{
    <div class="alert alert-info">
        @Model.Info.InfoMessage
    </div>
}

@if (Model.Info.ErrorMessage != null)
{
    <div class="alert alert-error">
        <strong>Ошибка</strong>: @Model.Info.ErrorMessage
    </div>
}
else if (Model != null)
{
    <p>
    <button type="button" class="btn button-back" title="Назад" value="Назад" onclick="history.back()"><i class="icon-arrow-left"></i><text> Назад</text></button>
    <a  class="btn" target="_blank" href="@Url.Action("Report", "CadetsData", new { cadetId = Model.Id })" ><i class="icon-print"></i><text> Печать</text></a>
    </p>
    
    <div class="cadet-info-card">
        <table class="info-card-markup">
            <tr>
                <td>
                    <div class="photo-container">
                        <span id="photo-div" onclick="">
                            @if (Model.Photo == null)
                            {
                                <text>Фото отсутствует</text>
                                <img id="photo-div-inner-image" class="img-polaroid" 
                                     src="@Url.Content("~/images/no-avatar.jpg")" alt="Фотография отсутствует"/>
                            }
                            else
                            {
                                <img id="photo-div-inner-image" class="img-polaroid" 
                                        src="data:image/png;base64,@Convert.ToBase64String(Model.Photo)" />
                            }
                        </span>

                    </div>
                </td>
                

                <td>
                    <span class="cadet-info-data">
                            <div>
                                <span class="cadet-info-label">Группа: </span>
                                <span><b>@Model.Group.CompiledGroupNumber</b></span>
                            </div>
                            <br/>
                            <div>
                                <span class="cadet-info-label">Фамилия: </span>
                                <span>@Model.LastName</span>
                            </div>
                            <div>
                                <span class="cadet-info-label">Имя: </span>
                                <span>@Model.FirstName</span>
                            </div>
                            <div>
                                <span class="cadet-info-label">Отчество: </span> 
                                <span>@Model.FathersName</span>
                            </div>
                            <br/>
                            <div>
                                <span class="cadet-info-label">Год поступления: </span> 
                                <span>@Model.Year</span>
                            </div>
                            <div>
                                <span class="cadet-info-label">Звание: </span> 
                                <span>@Model.Rank.Name</span>
                            </div>
                        </span>
                </td>
            </tr>
            

        </table>
        
    </div>
    
    <div class="cadet-info-graphics">
        <div class="cadet-info-graphic" id="columnGraph" style="width: 100%; height: 70%; margin: 0 2px"></div>
        <div class="cadet-info-graphic" id="columnGraphStacked" style="width: 100%; height: 70%; margin: 0 2px"></div>
    </div>
    
   
}

tags/Cadet.PhysicalAccounting 1.0/Cadet.PhysicalAccounting.Web/Views/CadetsData/Index.cshtml
@using Cadet.PhysicalAccounting.Web
@model Cadet.PhysicalAccounting.Web.Models.SessionData
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <p>
                Список курсантов
            </p>
        </div>
    </section>
}

@if (Model.Info.ErrorMessage != null)
{
    <div class="subpage-header">Список курсантов</div>
}
else
{
    <div class="subpage-header">@Model.Group.CompiledGroupNumber учебная группа</div>
    if (User.IsPriveleged())
    {
                <br/>
                 <button class="btn btn-success button-edit-all"
                       type="button" 
                       title="Ввод результатов" 
                       value="Ввод результатов"
                       onclick="location.href='@Url.Action("WriteResults", "CadetsData", new { groupId = Model.Group.Id }, null)'"
                       style="color:Black"
                  >
                      <i class="icon-pencil"></i>
                      <text>Ввод результатов</text>
                  </button>
                <br/>

    }
}

@if (Model.Info.InfoMessage != null)
{
    <div class="alert alert-info">
        @Model.Info.InfoMessage
    </div>
}

@{
    if (Model.Info.ErrorMessage != null)
    {
        <div class="alert alert-error">
            <strong>Ошибка</strong>: @Model.Info.ErrorMessage
        </div>
    }
    else
    {
        <br />
        if (Model.Cadets.Count == 0)
        {
        <text>Список курсантов пуст</text>
        }
        else
        {
            <table class="table table-bordered table-striped search-result">
            <thead>
                    <th>
                        №
                    </th>
                    <th class="search-result-fio">
                        ФИО
                    </th>
            </thead>
            @{ int index = 0;}
            @foreach (var cadet in Model.Cadets)
            {
                index++;
                <tr>
                    <td>
                        @index
                    </td>
                    <td>
                        @{
                string fio = cadet.LastName + " " + cadet.FirstName + " " + cadet.FathersName;
                            
                        }
                        @Html.ActionLink(fio, "Details", "CadetsData", new { cadetId = cadet.Id }, null)
                    </td>
                </tr>
            }
            </table>
        }
    }
    
}

tags/Cadet.PhysicalAccounting 1.0/Cadet.PhysicalAccounting.Web/Views/CadetsData/Report.cshtml
@using Cadet.PhysicalAccounting.Web.Models
@model Cadet.PhysicalAccounting.DBProxy.Cadet
@{
    Layout = null;
    ViewData["animation"] = false;
}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>Отчёт по группе @Model.Group.CompiledGroupNumber</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        @Styles.Render("~/Content/css")
        
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Styles.Render("~/bundles/highcharts")
        <script type="text/javascript" src="../../Scripts/highcharts/highcharts.js"></script>
        <script type="text/javascript" src="../../Scripts/highcharts/modules/exporting.js"></script>
    
        <style>
            body {
                width: 297mm;
                height: 210mm;
                /* to centre page on screen*/
                margin-left: auto;
                margin-right: auto;
            }
        </style>
        
        @Html.Partial("_ColumnGraphPartial", Model, ViewData)
    </head>
    
    <body onload="javascript:print();">
        <table id="report-container">
            <colgroup>
                <col width="12.5%">
                <col width="12.5%">
                <col width="12.5%">
                <col width="12.5%">
                
                <col width="12.5%">
                <col width="12.5%">
                <col width="12.5%">
                <col width="12.5%">
            </colgroup>
            <tbody>
                <tr>
                    <td id="report-photo-block" class="report-block" colspan="3">
                        <span class="cadet-info-photo">
                        @if (Model.Photo == null)
                        {
                            <text>Фото отсутствует</text>
                            <img id="report-photo" src="none" alt="Фотография отсутствует" />
                        }
                        else
                        {
                            <img id="report-photo"  
                                 src="data:image/png;base64,@Convert.ToBase64String(Model.Photo)" />
                        }
                    </span><span class="cadet-info-data">
                        <div>
                            <span class="cadet-info-label">Группа: </span><span><b>@Model.Group.CompiledGroupNumber</b></span>
                        </div>
                        <br />
                        <div>
                            <span class="cadet-info-label">Фамилия: </span><span>@Model.LastName</span>
                        </div>
                        <div>
                            <span class="cadet-info-label">Имя: </span><span>@Model.FirstName</span>
                        </div>
                        <div>
                            <span class="cadet-info-label">Отчество: </span><span>@Model.FathersName</span>
                        </div>
                        <br />
                        <div>
                            <span class="cadet-info-label">Год поступления: </span><span>@Model.Year</span>
                        </div>
                        <div>
                            <span class="cadet-info-label">Звание: </span><span>@Model.Rank.Name</span>
                        </div>
                    </span>
                </td>
                <td id="report-table-block" class="report-block" colspan="5">
                    <table id="norm-results" class="table table-bordered table-striped">
                        <thead>
                            <th class="number-cell-header">
                                № семестра
                            </th>
                            <th class="result-cell-header">@NormsTypes.Power</th>
                            <th class="result-cell-header">@NormsTypes.Agility</th>
                            <th class="result-cell-header">@NormsTypes.Speed</th>
                            <th class="result-cell-header">@NormsTypes.Endurance</th>
                            <th class="result-cell-header">@NormsTypes.Military</th>
                            <th class="result-cell-header">Общий балл</th>
                        </thead>
                        <tbody>
                            @{
                                var results = @Model.Results.OrderBy(o => o.Norm.Id);
                                var semesterResults = results.GroupBy(o => o.Semester.Number);
                                //semesterResults.First()
                            }
                            @foreach (var itSemRes in semesterResults)
                            {
                                var power = @itSemRes.SingleOrDefault(o => o.Norm.NormType.Id == @NormsTypes.PowerId);
                                var agility = @itSemRes.SingleOrDefault(o => o.Norm.NormType.Id == @NormsTypes.AgilityId);
                                var speed = @itSemRes.SingleOrDefault(o => o.Norm.NormType.Id == @NormsTypes.SpeedId);
                                var endurance = @itSemRes.SingleOrDefault(o => o.Norm.NormType.Id == @NormsTypes.EnduranceId);
                                var military = @itSemRes.SingleOrDefault(o => o.Norm.NormType.Id == @NormsTypes.MilitaryId);
                                <tr>
                                    <td class="result-cell">
                                        <b>@itSemRes.First().Semester.Number</b>
                                    </td>
                                    <td class="result-cell">
                                        @if (power != null)
                                        {
                                            <text>@power.Norm.Name (@power.Value)</text>
                                        }
                                        else
                                        {
                                            <text>-</text>
                                        }
                                    <td class="result-cell">
                                        @if (agility != null)
                                        {
                                            <text>@agility.Norm.Name (@agility.Value)</text>
                                        }
                                        else
                                        {
                                            <text>-</text>
                                        }
                                    </td>
                                    <td class="result-cell">
                                        @if (speed != null)
                                        {
                                            <text>@speed.Norm.Name (@speed.Value)</text>
                                        }
                                        else
                                        {<text>-</text>}
                                    </td>
                                    <td class="result-cell">
                                        @if (endurance != null)
                                        {
                                            <text>@endurance.Norm.Name (@endurance.Value)</text>
                                        }
                                        else
                                        {
                                            <text>-</text>
                                        }
                                    </td>
                                    <td class="result-cell">
                                        @if (military != null)
                                        {
                                            <text>@military.Norm.Name (@military.Value)</text>
                                        }
                                        else
                                        {
                                            <text>-</text>
                                        }
                                    </td>
                                    <td class="result-cell">
                                        @{
                                            var sum = ((power == null) ? 0 : power.Value)
                                                        + ((agility == null) ? 0 : agility.Value)
                                                        + ((speed == null) ? 0 : speed.Value)
                                                        + ((endurance == null) ? 0 : endurance.Value)
                                                        + ((military == null) ? 0 : military.Value);
                                            <text>@sum</text>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td id="report-graph1-block" class="report-block" colspan="4">
                    <div class="cadet-info-graphic" id="columnGraph">
                    </div>
                </td>
                <td id="report-graph2-block" class="report-block" colspan="4">
                    <div class="cadet-info-graphic" id="columnGraphStacked">
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</body>
</html>

tags/Cadet.PhysicalAccounting 1.0/Cadet.PhysicalAccounting.Web/Views/CadetsData/Search.cshtml
@model Cadet.PhysicalAccounting.Web.Models.SearchSessionData



@if (Model.Info.ErrorMessage != null)
{
    <div class="subpage-header">Во время поиска возникла ошибка</div>
}
else
{
    <div class="subpage-header">Результат поиска по запросу "@Model.SearchString" :</div>
}

@if (Model.Info.InfoMessage != null)
{
    <div class="alert alert-info">
        @Model.Info.InfoMessage
    </div>
}

@{
    if (Model.Info.ErrorMessage != null)
    {
        <div class="alert alert-error">
            <strong>Ошибка</strong>: @Model.Info.ErrorMessage
        </div>
    }
    else
    {
        <br />
        if (Model.Cadets.Count == 0)
        {
            <text>Поиск не дал результатов</text>
        }
        else
        {
            <text>@Model.Cadets.Count курсантов</text>
            <table class="table table-bordered table-striped search-result">
            <thead>
                    <th class="search-result-no">
                        №
                    </th>
                    <th class="search-result-fio">
                        ФИО
                    </th>
                    <th class="search-result-group">
                        Группа
                    </th>
            </thead>
            @{int index = 0;}
            @foreach (var cadet in Model.Cadets)
            {
                string fio = cadet.LastName + " " + cadet.FirstName + " "  + cadet.FathersName;
                index++;             
                  <tr>
                   <td class="search-result-no">
                        @index
                    </td>
                    <td class="search-result-fio">
                        @Html.ActionLink(fio, "Details", "CadetsData", new { cadetId = cadet.Id }, null) 
                    </td>
                    <td class="search-result-group">
                        @Html.ActionLink(cadet.Group.CompiledGroupNumber, "Index", "CadetsData", new { groupId = cadet.GroupId }, null) 
                    </td>
                  </tr>
                
                                    
            }
            </table>
    }
    }
    
}

tags/Cadet.PhysicalAccounting 1.0/Cadet.PhysicalAccounting.Web/Views/CadetsData/WriteResults.cshtml
@model Cadet.PhysicalAccounting.Web.Models.SessionData
@section scripts
{
    <script type="text/javascript" src="~/Scripts/jquery.validate.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    <script type="text/javascript">
        $(function() {
            $("#SemesterId").change(function() {
                $("#cadets-results-container").load("@Url.Action("GetResults", "CadetsData")/?groupId=" + @Model.GroupId + "&semesterId=" + $(this).val());
            });
        });
    </script>

    <script type="text/javascript">
       $("#cadets-results-container").load("@Url.Action("GetResults", "CadetsData")/?groupId=" + @Model.GroupId + "&semesterId=" + $("#SemesterId").val());
    </script>
}

@Html.HiddenFor(o => o.GroupId)
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    if (Model.Info.ErrorMessage != null)
    {
    <div class="subpage-header">
        Список курсантов - внесение результатов</div>
    }
    else
    {
    <div class="subpage-header">
        @Model.Group.CompiledGroupNumber учебная группа - внесение результатов</div>
    }
    
    <p />
    if (Model.Info.InfoMessage != null)
    {
        <div class="alert alert-info">
            @Model.Info.InfoMessage
        </div>
    }
    if (Model.Info.ErrorMessage != null)
    {
        <div class="alert alert-error">
            <strong>Ошибка</strong>: @Model.Info.ErrorMessage
        </div>
    }
    else
    {
        if (Model.Info.SuccessMessage != null)
        {
        <div class="alert alert-success">
            @Model.Info.SuccessMessage
        </div>
        }
    }

    <p/>
    
    <div class="cadet-semester-dropdown">
        <div class="cadet-semester-header">Номер семестра
            @Html.DropDownListFor(model => model.SemesterId, Model.Semesters)
            @Html.ValidationMessageFor(model => model.SemesterId, "Выберете номер семестра для выбора данных")
        </div>
    </div>


    <div id="cadets-results-container">
    </div>


    <fieldset>
        <legend>SessionData</legend>
        <p>
            <button class="btn btn-success button-save" type="submit" value="Сохранить" ><i class="icon-ok  icon-white"></i><text> Сохранить изменения</text></button>
            <button type="button" class="btn button-back" title="Назад" value="Назад" onclick="location.href='@Url.Action("Index", "CadetsData", new { groupId = Model.Group.Id }, null)'" ><i class="icon-arrow-left"></i><text> Назад</text></button>
        </p>
    </fieldset>
}