trunk/Cadet.PhysicalAccounting/Cadet.PhysicalAccounting.Web/Controllers/FacultyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cadet.PhysicalAccounting.DBProxy;

namespace Cadet.PhysicalAccounting.Web.Controllers
{
    public class FacultyController : Controller
    {
        private DBContext db = new DBContext();

        //
        // GET: /Faculty/

        public ActionResult Index()
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            return View(db.Faculties.ToList().OrderBy(f=>f.Number));
        }

        //
        // GET: /Faculty/Create

        public ActionResult Create()
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            return View();
        }

        //
        // POST: /Faculty/Create

        [HttpPost]
        public ActionResult Create(Faculty faculty)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            if (ModelState.IsValid)
            {
                db.Faculties.AddObject(faculty);
                db.SaveChanges();
                FacultyTreeMaker.RefreshFacultyTreeModel();
                return RedirectToAction("Index");
            }

            return View(faculty);
        }

        //
        // GET: /Faculty/Edit/5

        public ActionResult Edit(int id = 0)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Faculty faculty = db.Faculties.Single(f => f.Id == id);
            if (faculty == null)
            {
                return HttpNotFound();
            }
            return View(faculty);
        }

        //
        // POST: /Faculty/Edit/5

        [HttpPost]
        public ActionResult Edit(Faculty faculty)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            if (ModelState.IsValid)
            {
                db.Faculties.Attach(faculty);
                db.ObjectStateManager.ChangeObjectState(faculty, EntityState.Modified);
                db.SaveChanges();
                FacultyTreeMaker.RefreshFacultyTreeModel();
                return RedirectToAction("Index");
            }
            return View(faculty);
        }

        //
        // GET: /Faculty/Delete/5

        public ActionResult Delete(int id = 0)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Faculty faculty = db.Faculties.Single(f => f.Id == id);
            if (faculty == null)
            {
                return HttpNotFound();
            }
            return View(faculty);
        }

        //
        // POST: /Faculty/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Faculty faculty = db.Faculties.Single(f => f.Id == id);

            foreach (var course in faculty.Courses.ToList())
            {
                foreach (var group in course.Groups.ToList())
                {
                    foreach (var cadet in group.Cadets.ToList())
                    {
                        foreach (var result in cadet.Results.ToList())
                        {
                            db.Results.DeleteObject(result);
                        }
                        db.Cadets.DeleteObject(cadet);
                    }
                    db.Groups.DeleteObject(group);
                }
                db.Courses.DeleteObject(course);
            }
            db.Faculties.DeleteObject(faculty);

            db.SaveChanges();
            FacultyTreeMaker.RefreshFacultyTreeModel();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

trunk/Cadet.PhysicalAccounting/Cadet.PhysicalAccounting.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cadet.PhysicalAccounting.Web.Models;

namespace Cadet.PhysicalAccounting.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var tree = FacultyTreeMaker.CurrentFacultyTree;
            ViewBag.Message = "Физическая подготовка курсантов";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Приложение для сбора статистики физического развития курсантов";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Обратная связь";

            return View();
        }

        public ActionResult Generate()
        {
            var testDataGenerator = new TestDataGenerator();
            testDataGenerator.FillDB();

            return View("Index");
        }

        public ActionResult Edit()
        {
            return View();
        }
    }
}

trunk/Cadet.PhysicalAccounting/Cadet.PhysicalAccounting.Web/Controllers/NormController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cadet.PhysicalAccounting.DBProxy;

namespace Cadet.PhysicalAccounting.Web.Controllers
{
    public class NormController : Controller
    {
        private DBContext db = new DBContext();

        //
        // GET: /Norm/

        public ActionResult Index()
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            var norms = db.Norms.Include("NormType");
            return View(norms.ToList().OrderBy(x=>x.NormTypeId).ThenBy(x=>x.Name));
        }

        //
        // GET: /Norm/Create

        public ActionResult Create()
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            ViewBag.NormTypeId = new SelectList(db.NormTypes, "Id", "Name");
            return View();
        }

        //
        // POST: /Norm/Create

        [HttpPost]
        public ActionResult Create(Norm norm)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            if (ModelState.IsValid)
            {
                db.Norms.AddObject(norm);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.NormTypeId = new SelectList(db.NormTypes, "Id", "Name", norm.NormTypeId);
            return View(norm);
        }

        //
        // GET: /Norm/Edit/5

        public ActionResult Edit(int id = 0)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Norm norm = db.Norms.Single(n => n.Id == id);
            if (norm == null)
            {
                return HttpNotFound();
            }
            ViewBag.NormTypeId = new SelectList(db.NormTypes, "Id", "Name", norm.NormTypeId);
            return View(norm);
        }

        //
        // POST: /Norm/Edit/5

        [HttpPost]
        public ActionResult Edit(Norm norm)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            if (ModelState.IsValid)
            {
                db.Norms.Attach(norm);
                db.ObjectStateManager.ChangeObjectState(norm, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.NormTypeId = new SelectList(db.NormTypes, "Id", "Name", norm.NormTypeId);
            return View(norm);
        }

        //
        // GET: /Norm/Delete/5

        public ActionResult Delete(int id = 0)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Norm norm = db.Norms.Single(n => n.Id == id);
            if (norm == null)
            {
                return HttpNotFound();
            }
            return View(norm);
        }

        //
        // POST: /Norm/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!User.IsPriveleged())
            {
                return View("AccessDenied");
            }

            Norm norm = db.Norms.Single(n => n.Id == id);
            db.Norms.DeleteObject(norm);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

trunk/Cadet.PhysicalAccounting/Cadet.PhysicalAccounting.Web/Controllers/SemesterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cadet.PhysicalAccounting.DBProxy;

namespace Cadet.PhysicalAccounting.Web.Controllers
{
    public class SemesterController : Controller
    {
        private DBContext db = new DBContext();

        //
        // GET: /Semester/

        public ActionResult Index()
        {
            return View(db.Semesters.ToList());
        }

        //
        // GET: /Semester/Details/5

        public ActionResult Details(byte id = 0)
        {
            Semester semester = db.Semesters.Single(s => s.Id == id);
            if (semester == null)
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        //
        // GET: /Semester/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Semester/Create

        [HttpPost]
        public ActionResult Create(Semester semester)
        {
            if (ModelState.IsValid)
            {
                db.Semesters.AddObject(semester);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(semester);
        }

        //
        // GET: /Semester/Edit/5

        public ActionResult Edit(byte id = 0)
        {
            Semester semester = db.Semesters.Single(s => s.Id == id);
            if (semester == null)
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        //
        // POST: /Semester/Edit/5

        [HttpPost]
        public ActionResult Edit(Semester semester)
        {
            if (ModelState.IsValid)
            {
                db.Semesters.Attach(semester);
                db.ObjectStateManager.ChangeObjectState(semester, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(semester);
        }

        //
        // GET: /Semester/Delete/5

        public ActionResult Delete(byte id = 0)
        {
            Semester semester = db.Semesters.Single(s => s.Id == id);
            if (semester == null)
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        //
        // POST: /Semester/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(byte id)
        {
            Semester semester = db.Semesters.Single(s => s.Id == id);
            db.Semesters.DeleteObject(semester);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

trunk/Cadet.PhysicalAccounting/Cadet.PhysicalAccounting.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "Справка";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Как пользоваться программой
    </p>


</article>

<!-- возможно это что-то нужное, пока заккоментил
<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>
-->

trunk/Cadet.PhysicalAccounting/Cadet.PhysicalAccounting.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<!--
<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>
-->
<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Техническая поддержка:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
</section>

<!--
<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>
-->

trunk/Cadet.PhysicalAccounting/Cadet.PhysicalAccounting.Web/Views/Home/Edit.cshtml
@{
    ViewBag.Title = "Редактирование";
}



<h2>Редактирование</h2>

<br/>

<ul class="edit-page-list">
    
    <li>
        <a href="@Url.Action("Index", "Faculty")"><i class="icon-pencil"></i> Редактировать факультеты, курсы и группы</a>
    </li>

    <li>
        <a href="@Url.Action("Index", "Norm")"><i class="icon-pencil"></i> Редактировать нормативы</a>
    </li>

    <li>
        <a href="@Url.Action("Index", "Semester")"><i class="icon-pencil"></i> Редактировать пороговые значения</a>
    </li>

    <li>
        <a href="@Url.Action("Index", "NormType")"><i class="icon-pencil"></i> Редактировать названия нормативов</a>
    </li>
</ul>
<br/>


<p>
    <button type="button" class="btn btn-info button-back" title="Назад" value="Назад" style="color:Black" onclick="location.href='@Url.Action("Index","Home")'"><i class="icon-arrow-left"> </i> <text> Назад</text></button>
</p>

trunk/Cadet.PhysicalAccounting/Cadet.PhysicalAccounting.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                Результаты курсантов по физической подготовке.
            </p>
        </div>
    </section>
}
<h3>Для начала работы:</h3>
<ol class="round">
    <li class="one">
        <h5>шаг</h5>
        <p>
        Добавьте факультеты, группы и курсантов
        </p>
    </li>

    <li class="two">
        <h5>шаг</h5>
        <p>
        Добавьте результаты курсантов
        </p>
    </li>

    <li class="three">
        <h5>шаг</h5>
        <p>
        Просматривайте статистику их развития
        </p>
    </li>
</ol>